name: 'aegis_datalake'
version: '0.10.0'
config-version: 2

profile: 'aegis_datalake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aegis_datalake:
    +materialized: view
    gold:
      +materialized: table
