"""
aegis.security.sops.integration — SOPS + age envelope encryption helpers.

Wraps the ``sops`` CLI to encrypt and decrypt ``.env.sops.yaml`` files.
Age is used as the encryption backend (pure-Go, no GPG daemon required).

Workflow::

    # First-time setup (generate age key):
    from aegis.security.sops import SopsManager
    mgr = SopsManager()
    mgr.generate_age_key()          # saves to ~/.config/sops/age/keys.txt
    mgr.init_sops_config(".")       # writes .sops.yaml

    # Encrypt a plaintext .env file:
    mgr.encrypt_env(".env", ".env.sops.yaml")

    # Decrypt for use (in memory only, never writes to disk):
    env_vars = mgr.decrypt_to_dict(".env.sops.yaml")

FREE-TIER PATH: sops + age are both Apache-2.0 licensed OSS tools.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import structlog

_log = structlog.get_logger(__name__)

_DEFAULT_AGE_KEY_DIR = Path.home() / ".config" / "sops" / "age"
_DEFAULT_AGE_KEY_FILE = _DEFAULT_AGE_KEY_DIR / "keys.txt"
_SOPS_CONFIG_TEMPLATE = """\
# .sops.yaml — AEGIS Pulse SOPS configuration
# Generated by aegis.security.sops.integration
# Commit this file to git; never commit plaintext secrets.
creation_rules:
  - path_regex: \\.env\\.sops\\.yaml$
    age: >-
      {age_pubkey}
"""


class SopsManager:
    """Manages SOPS + age encryption for secrets files.

    Parameters
    ----------
    age_key_file:
        Path to the age private key file.
    sops_config_path:
        Path to the ``.sops.yaml`` configuration file.
    """

    def __init__(
        self,
        age_key_file: str | Path = _DEFAULT_AGE_KEY_FILE,
        sops_config_path: str | Path = ".sops.yaml",
    ) -> None:
        self._age_key_file = Path(age_key_file)
        self._sops_config = Path(sops_config_path)

    # ── Prerequisite checks ───────────────────────────────────────────────── #

    def check_dependencies(self) -> dict[str, bool]:
        """Return availability of required CLI tools."""
        return {
            "sops": shutil.which("sops") is not None,
            "age": shutil.which("age") is not None,
            "age-keygen": shutil.which("age-keygen") is not None,
        }

    # ── Key management ────────────────────────────────────────────────────── #

    def generate_age_key(self, *, force: bool = False) -> str:
        """Generate a new age key pair and save to ``_age_key_file``.

        Parameters
        ----------
        force:
            Overwrite existing key file if present.

        Returns
        -------
        str
            The public key (``age1...``), safe to commit in ``.sops.yaml``.

        Raises
        ------
        FileExistsError
            If the key file exists and ``force=False``.
        RuntimeError
            If ``age-keygen`` is not installed.
        """
        if self._age_key_file.exists() and not force:
            raise FileExistsError(
                f"[AEGIS-SEC-0091] Age key already exists: {self._age_key_file}. "
                "Use force=True to overwrite."
            )
        if not shutil.which("age-keygen"):
            raise RuntimeError(
                "[AEGIS-SEC-0092] age-keygen not found. "
                "Install with: apt install age OR brew install age"
            )

        self._age_key_file.parent.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            ["age-keygen", "-o", str(self._age_key_file)],
            capture_output=True,
            text=True,
            check=True,
        )
        # age-keygen prints the public key to stderr
        pubkey = ""
        for line in result.stderr.splitlines():
            if line.startswith("Public key:"):
                pubkey = line.split(":", 1)[1].strip()
                break

        # Restrict permissions on the key file
        self._age_key_file.chmod(0o600)
        _log.info("sops.age_key_generated", path=str(self._age_key_file))
        return pubkey

    def get_public_key(self) -> str:
        """Extract the public key from the existing age key file."""
        if not self._age_key_file.exists():
            raise FileNotFoundError(
                f"[AEGIS-SEC-0093] Age key not found: {self._age_key_file}. "
                "Run generate_age_key() first."
            )
        for line in self._age_key_file.read_text().splitlines():
            if line.startswith("# public key:"):
                return line.split(":", 1)[1].strip()
        raise ValueError(
            f"[AEGIS-SEC-0094] Could not parse public key from {self._age_key_file}"
        )

    # ── SOPS config ───────────────────────────────────────────────────────── #

    def init_sops_config(
        self,
        project_root: str | Path = ".",
        *,
        force: bool = False,
    ) -> Path:
        """Write a ``.sops.yaml`` configuration file.

        Parameters
        ----------
        project_root:
            Directory to write the config into.
        force:
            Overwrite existing config.

        Returns
        -------
        Path
            Path to the written ``.sops.yaml``.
        """
        config_path = Path(project_root) / ".sops.yaml"
        if config_path.exists() and not force:
            _log.info("sops.config_exists", path=str(config_path))
            return config_path

        pubkey = self.get_public_key()
        config_path.write_text(
            _SOPS_CONFIG_TEMPLATE.format(age_pubkey=pubkey),
            encoding="utf-8",
        )
        _log.info("sops.config_written", path=str(config_path))
        return config_path

    # ── Encrypt / Decrypt ─────────────────────────────────────────────────── #

    def encrypt_env(
        self,
        plaintext_path: str | Path,
        output_path: str | Path | None = None,
    ) -> Path:
        """Encrypt a plaintext ``.env`` file into ``.env.sops.yaml``.

        Parameters
        ----------
        plaintext_path:
            Source ``.env`` file.
        output_path:
            Destination encrypted file; defaults to ``<input>.sops.yaml``.

        Returns
        -------
        Path
            Path of the encrypted output file.
        """
        plaintext_path = Path(plaintext_path)
        if output_path is None:
            output_path = plaintext_path.parent / (plaintext_path.name + ".sops.yaml")
        output_path = Path(output_path)

        env = {**os.environ, "SOPS_AGE_KEY_FILE": str(self._age_key_file)}
        subprocess.run(
            [
                "sops",
                "--encrypt",
                "--input-type", "dotenv",
                "--output-type", "yaml",
                "--output", str(output_path),
                str(plaintext_path),
            ],
            check=True,
            capture_output=True,
            env=env,
        )
        _log.info("sops.encrypted", source=str(plaintext_path), dest=str(output_path))
        return output_path

    def decrypt_to_dict(self, encrypted_path: str | Path) -> dict[str, str]:
        """Decrypt a SOPS-encrypted env file into a plain dict.

        The decrypted content is never written to disk.

        Returns
        -------
        dict[str, str]
            Environment variable key/value pairs.
        """
        encrypted_path = Path(encrypted_path)
        if not encrypted_path.exists():
            raise FileNotFoundError(
                f"[AEGIS-SEC-0095] Encrypted file not found: {encrypted_path}"
            )

        env = {**os.environ, "SOPS_AGE_KEY_FILE": str(self._age_key_file)}
        result = subprocess.run(
            [
                "sops",
                "--decrypt",
                "--output-type", "dotenv",
                str(encrypted_path),
            ],
            capture_output=True,
            text=True,
            check=True,
            env=env,
        )

        out: dict[str, str] = {}
        for line in result.stdout.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip().strip('"').strip("'")
        _log.info("sops.decrypted", path=str(encrypted_path), keys=len(out))
        return out

    def inject_to_env(self, encrypted_path: str | Path) -> None:
        """Decrypt and inject variables directly into ``os.environ``.

        Use in process startup (e.g., ``aegis up``) so child processes
        inherit the decrypted variables without writing to disk.
        """
        for k, v in self.decrypt_to_dict(encrypted_path).items():
            os.environ.setdefault(k, v)
        _log.info("sops.injected_to_env", path=str(encrypted_path))
