"""
alembic/env.py
==============

Alembic environment script for AEGIS Pulse.

Two unusual things compared to a stock template:

1. **Raw SQL migrations.** Our primary migration format is hand-written
   ``.sql`` files under ``db/migrations/`` (e.g. ``0001_init.sql``).
   These are easier to review than autogenerated Alembic ops, and they
   work in emergencies without a Python interpreter. Alembic's own
   ``versions/`` directory is reserved for migrations that genuinely
   need Python (e.g. data backfills involving vector math).

   The "raw SQL" runner below applies any unapplied ``db/migrations/*.sql``
   file in order, tracking applied revisions in a small auxiliary table
   ``aegis_sql_revisions``. This means you can run *both* alembic-managed
   migrations and raw SQL migrations from a single ``alembic upgrade head``.

2. **DSN comes from settings(), not alembic.ini.** We never put a real
   DSN in a checked-in config file.

Usage::

    # Apply everything (raw SQL + alembic versions)
    alembic upgrade head

    # Generate a new Python migration (rare)
    alembic revision -m "add prediction tables"

    # Show what would run without running it
    alembic upgrade head --sql

Author: AEGIS Pulse foundation team
Phase:  1 — Foundation
"""

from __future__ import annotations

import asyncio
import logging
import re
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

# ---------------------------------------------------------------------
# Make ``src`` importable so we can reach `aegis.config`.
# ---------------------------------------------------------------------
_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent
sys.path.insert(0, str(_REPO_ROOT / "src"))

from aegis.config import settings  # noqa: E402  (after sys.path mutation)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.aegis")

# ---------------------------------------------------------------------
# We have no SQLAlchemy ORM models; raw SQL only. Set ``target_metadata``
# to ``None`` so autogenerate yields empty migrations rather than trying
# to introspect.
# ---------------------------------------------------------------------
target_metadata = None


# ---------------------------------------------------------------------
# Raw SQL migration runner
# ---------------------------------------------------------------------

_RAW_SQL_DIR = _REPO_ROOT / "db" / "migrations"

# Migration files that are SQLite-only / informational and must NOT be executed
# against Postgres (their real schema is created at runtime in Python).
_INFORMATIONAL_REVISIONS = frozenset({"0010_catalog"})
_REV_TABLE = "aegis_sql_revisions"
_FILENAME_RE = re.compile(r"^(\d{4})_[a-z0-9_]+\.sql$")


def _list_raw_sql_files() -> list[Path]:
    """Return all ``NNNN_*.sql`` files in ``db/migrations`` in sort order.

    The filename grammar is ``\\d{4}_lowercase_with_underscores.sql``.
    Anything else in that directory is ignored with a warning so that a
    stray editor swap-file never gets executed against the database.
    """
    if not _RAW_SQL_DIR.exists():
        return []
    out: list[Path] = []
    for path in sorted(_RAW_SQL_DIR.iterdir()):
        if path.is_dir():
            continue
        if path.stem in _INFORMATIONAL_REVISIONS:
            # SQLite-only DDL kept for documentation; the real schema is built
            # at runtime in Python. Never execute it against Postgres.
            continue
        if _FILENAME_RE.match(path.name):
            out.append(path)
        else:
            logger.warning(
                "Skipping non-conforming migration filename: %s", path.name
            )
    return out


def _clean_sql(sql: str) -> str:
    """Strip psql client metacommands and top-level transaction wrappers.

    psql's \\echo (and other backslash commands) are client-side only and
    are not valid SQL.  The top-level BEGIN/COMMIT in our migration files
    are redundant when SQLAlchemy manages the transaction.
    """
    lines = []
    for line in sql.splitlines():
        if line.lstrip().startswith("\\"):
            continue
        # Only strip a line whose *entire* content is BEGIN; or COMMIT;
        # (case-insensitive).  This leaves BEGIN/COMMIT inside $$…$$ PL/pgSQL
        # blocks untouched because those lines have surrounding code.
        if line.strip().upper() in ("BEGIN;", "COMMIT;"):
            continue
        lines.append(line)
    return "\n".join(lines)


# ---------------------------------------------------------------------
# Standard Alembic offline / online entry points
# ---------------------------------------------------------------------

def _resolve_pg_dsn() -> str:
    """Return the raw ``postgresql://`` DSN for direct asyncpg connections.

    asyncpg.connect() does not understand SQLAlchemy scheme suffixes like
    ``+asyncpg``, so we normalise back to the standard scheme.
    """
    explicit = config.get_main_option("sqlalchemy.url")
    raw = explicit if explicit else settings().pg_dsn_str
    return re.sub(r"^postgresql(\+\w+)?://", "postgresql://", raw)


def _resolve_sqlalchemy_url() -> str:
    """Return the ``postgresql+asyncpg://`` URL for SQLAlchemy's async engine."""
    explicit = config.get_main_option("sqlalchemy.url")
    raw = explicit if explicit else settings().pg_dsn_str
    return re.sub(r"^postgresql(\+\w+)?://", "postgresql+asyncpg://", raw)


def run_migrations_offline() -> None:
    """Emit SQL to stdout without touching a database.

    Offline mode skips raw SQL execution (we'd have nowhere to write the
    revision row) and only emits Alembic-managed Python migrations.
    """
    url = _resolve_sqlalchemy_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _run_phase_b(conn: Connection) -> None:
    """Phase B: Alembic Python migrations (called via run_sync)."""
    context.configure(
        connection=conn,
        target_metadata=target_metadata,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply raw SQL files first, then Alembic Python migrations.

    Phase A uses a direct asyncpg connection (not SQLAlchemy) because
    asyncpg's simple-query protocol is required for multi-statement SQL
    files.  SQLAlchemy's asyncpg dialect always uses the extended-query
    (prepared statement) protocol, which rejects multiple commands.

    Phase B uses a SQLAlchemy async engine so Alembic's own migration
    runner gets the typed Connection it expects.
    """
    import asyncpg  # local import — only needed during migrations

    async def _run() -> None:
        # --- Phase A: raw SQL via direct asyncpg ----------------------------
        conn_a = await asyncpg.connect(_resolve_pg_dsn())
        try:
            await conn_a.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_REV_TABLE} (
                    revision   text PRIMARY KEY,
                    applied_at timestamptz NOT NULL DEFAULT NOW()
                )
                """
            )
            rows = await conn_a.fetch(f"SELECT revision FROM {_REV_TABLE}")  # noqa: S608
            applied = {row["revision"] for row in rows}

            for path in _list_raw_sql_files():
                revision = path.stem
                if revision in applied:
                    continue
                sql = _clean_sql(path.read_text(encoding="utf-8"))
                logger.info("Applying raw SQL migration: %s", revision)
                # No parameters → asyncpg uses the simple-query protocol,
                # which supports multiple statements in one call.
                await conn_a.execute(sql)
                await conn_a.execute(
                    f"INSERT INTO {_REV_TABLE} (revision) VALUES ($1)", revision  # noqa: S608
                )
                logger.info("Applied: %s", revision)
        finally:
            await conn_a.close()

        # --- Phase B: Alembic Python migrations via SQLAlchemy async --------
        engine = create_async_engine(_resolve_sqlalchemy_url(), pool_pre_ping=True)
        try:
            async with engine.connect() as async_conn:
                await async_conn.run_sync(_run_phase_b)
        finally:
            await engine.dispose()

    asyncio.run(_run())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
